# Generated by Django 4.0.1 on 2022-01-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='saved_articles',
            field=models.CharField(default='{}', max_length=100000),
        ),
    ]
