# Generated by Django 4.0.1 on 2022-01-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_article_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='saved_articles',
            field=models.CharField(default='[]', max_length=100000),
        ),
    ]
