# Generated by Django 4.0.2 on 2022-02-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_reader_saved_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Anonymous', max_length=122),
        ),
        migrations.AddField(
            model_name='comment',
            name='blogname',
            field=models.CharField(default='origin_13_jan_22', max_length=300),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default='1645725470.9460325', max_length=300),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='Bruh', max_length=2000),
        ),
    ]
